meething/meething

- src/assets/js/helpers.js
- src/assets/js/rtc.js
- src/index.html
- Refactored the screenshare-methods to be more concise  
- moved and renamed replaceVideoTrack to replaceVideoTrackForPeers
> Refactored #10 (MR #12)

- src/assets/js/emitter.js
- src/assets/js/helpers.js
- src/assets/js/presence.js
- src/assets/js/rtc.js
- src/index.html
Only available when in the room and by default hidden. Also this reduces the Gun instances from 3 to 1 in the app, so better maintainable.
see glitch version here:
https://meething-webrtc-qvdev.glitch.me/?room=qvdev
> Refactor presence list and reduce gun instances to 1 in the app

- meething.config.js
- src/app.js
- src/assets/js/rtc.js
Adding a pm2 script to start the server as boilerplate
> WIP: PM2 config

- src/assets/js/metadata.js
- src/assets/js/rtc.js
so we can sent information to other clients socketId and pid are send along every time
> Add metadata channel

- src/assets/js/helpers.js
- src/assets/js/metadata.js
- src/assets/js/rtc.js
- src/index.html
Please check here 
https://meething-qvdev.herokuapp.com/
double test if you hear yourself so try wit other particpants
> Added simple audio recording for meeting

- src/assets/css/snackbar.css
- src/assets/js/helpers.js
- src/assets/js/metadata.js
- src/assets/js/rtc.js
- src/index.html
> Add simple snackbar to notify users

- src/assets/js/helpers.js
- src/assets/js/rtc.js
- src/assets/js/soundmeter.js
- Soundmeter optimised
- Poster removed once playing
- Reduce calls to array
> Small improvements

- src/index.html
Sometimes specially with mute I got some glitches
> <i class did not really work and seems not needed.

- src/assets/js/helpers.js
- src/assets/js/rtc.js
> Fix media recording, and bring down to one place

- src/assets/js/presence.js
- src/assets/js/rtc.js
Mix of @QVDev patch in PR #101 and live testing patches
> Presence + GC Fixes

- src/assets/js/chatevents.js
- src/assets/js/rtc.js
Trying here hope this follows a bit of what we discussed earlier today.
> Chat command, such as help and timezones :)

- src/assets/js/config.js
- src/assets/js/events.js
- src/assets/js/main.js
- src/assets/js/modal.js
- src/index.html
Please check if you can enter the room with config/autoload false and only upon clicking Let's Go your cams etc get initialized.
> ee, autoload fixes, stuff overlooked

- src/assets/js/sfu/sfu.js
- src/assets/js/soundmeter.js
- src/index.html
Reattaching the soundMeter script to the SFU stream object.
TODO: emit event to mesh @Dletta
> Fix soundmeter for SFU

- src/assets/js/sfu/room.js
detecting ready state when transport fails in the try catch in room.js
Please test if this fixes is for chrome and firefox
> Possible Fix for SFU issue

- src/assets/js/sfu/sfu.js
> screen sharing constraints

- src/assets/js/sfu/peer.js
- src/assets/js/sfu/room.js
From here we can build upon to make it use mesh instead of retry fails
> Add better failsafe of websocket not able to connect. 

- src/assets/css/app.css
- src/assets/css/dragable.css
- src/assets/css/grid-stage.css
- src/assets/js/connection.js
- src/assets/js/helpers.js
- src/assets/js/mesh/mesh.js
- src/assets/js/observer.js
- src/assets/js/uex.js
- src/index.html
SHOULD dynamically load and unload additional css classes to control the grid looks/behavior
> WIP: Speaker stage 

- src/assets/js/modal.js
- src/assets/js/uex.js
fixes issue #178 , multiple permission requests on device selection menu.
Jabis suggested solution.
QvDev if you can make sure it doesn't break anything in chrome.
> fix issue #178

- src/assets/js/modal.js
> Update modal.js - fixes undefined I believe

- src/assets/js/ui/pipmode.js
And for  not supported pip browsers use full screen
> Make sure to take the first remote screen

- src/assets/js/sfu/sfu.js
- src/assets/js/sfu/video.js
muted video > 4 participants start muted audio/video > 12 participants
> Start muted 

- src/assets/js/chat.js
and returning without showInChat if no m…essage
> help text for /share command

- src/assets/js/chat.js
- src/assets/js/helpers.js
- src/assets/js/main.js
- src/assets/js/uex.js
> Meething new options

- src/assets/css/app.css
- src/index.html
Added link for feedback button
> added feedback button

- index.html
- src/assets/js/config.js
- src/assets/js/sfu/room.js
- src/index.html
this will make the app static runnable see for example:
https://meething.github.io/meething/
Idea is to have this static available for mesh only this will make it really easy to deploy and possibly getting rid of hosting it somewhere else and we can add a custom domain here as well.
> Make it work for gh-pages as a static website

- src/assets/js/mesh/mesh.js
Fix mesh.js try setting `this.SFU_ENABLED = true;` in main.js
> Fix mesh.js

- src/assets/js/chat.js
Someone could not join because of the use of experimental js `roomdata?.data` this is a small fix for that - also added a TODO to the mute, should force mute you there
> Fix from feedback

- src/assets/js/config.js
- src/assets/js/connection.js
- src/assets/js/helpers.js
- src/assets/js/mesh/mesh.js
- src/assets/js/sfu/sfu.js
- src/assets/js/ui/toggles.js
This includes fix for sending it to early the event, now when joined muted we see the new coming as muted as well. Auto mute is now 10 and configurable in config.js and will mute both audio and video directly.
> Show in the video-widget muted state

- src/assets/js/helpers.js
Added additional Try Catch for UI functions
> Make stuff not break when using helpers

- src/assets/js/plugins/pose/camera.js
- src/assets/js/plugins/pose/resources/illustration/lego.svg
- src/assets/js/uex.js
> Add Lego avatar

- src/assets/js/main.js
- src/index.html
Conditional exit menu `/?exit=true` to be displayed instead of the login page upon exit. Includes a "back" button to join the meething again.
> Exit Menu block

- README.md
I hope this removes a bit of ambiguity. Silly me: I forgot to remove the old text first. So one of the changes is split across two commits.
> Improve README.md (Clarify SSL certificate instructions, Add pm2 installation)

- src/assets/css/app.css
- src/assets/js/uex.js
- src/index.html
Removed Avatar Button, made GO button bigger, changed reset button to say Reset, removed one mediaStream call to fix the issue with 'devices' not coming back right, fixed overlap on the option button
> Couple of Updates
